version: 0.0
os: linux

files:
  - source: /
    # use aws linux
    destination: /home/ec2-user/dwella-ng
    overwrite: true

permissions:
  - object: /home/ec2-user/dwella-ng
    pattern: '**'
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/create_env.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ec2-user
    - location: scripts/validate_service.sh
      timeout: 300
      runas: ec2-user
